gui:
  title: "<gradient:#FFD700:#FFA500>✨ Negozio HiddenCoins ✨</gradient>"
  size: 54
  decoration:
    material: BLACK_STAINED_GLASS_PANE
    name: " "

coin-packages:
  small:
    name: "<gradient:#90EE90:#32CD32>Pacchetto Piccolo</gradient>"
    lore:
      - ""
      - "<gradient:#FFFFFF:#E0E0E0>Acquista</gradient> &e100 HiddenCoins"
      - ""
      - "<gradient:#FFD700:#FFA500>► Prezzo:</gradient> &a{price}"
      - ""
      - "<gradient:#00FF00:#00CC00>✦ Clicca per acquistare! ✦</gradient>"
    material: GOLD_NUGGET
    slot: 20
    price: 1000.0
    coins: 100

  medium:
    name: "<gradient:#87CEEB:#4682B4>Pacchetto Medio</gradient>"
    lore:
      - ""
      - "<gradient:#FFFFFF:#E0E0E0>Acquista</gradient> &e500 HiddenCoins"
      - "<gradient:#FFD700:#FFA500>✨ Risparmia il 10% ✨</gradient>"
      - ""
      - "<gradient:#FFD700:#FFA500>► Prezzo:</gradient> &a{price}"
      - ""
      - "<gradient:#00FF00:#00CC00>✦ Clicca per acquistare! ✦</gradient>"
    material: GOLD_INGOT
    slot: 22
    price: 4500.0
    coins: 500

  large:
    name: "<gradient:#DA70D6:#8B008B>Pacchetto Grande</gradient>"
    lore:
      - ""
      - "<gradient:#FFFFFF:#E0E0E0>Acquista</gradient> &e1000 HiddenCoins"
      - "<gradient:#FFD700:#FFA500>⭐ Risparmia il 20% ⭐</gradient>"
      - ""
      - "<gradient:#FFD700:#FFA500>► Prezzo:</gradient> &a{price}"
      - ""
      - "<gradient:#00FF00:#00CC00>✦ Clicca per acquistare! ✦</gradient>"
    material: GOLD_BLOCK
    slot: 24
    price: 8000.0
    coins: 1000

shop-items:
  elite:
    name: "<gradient:#FFD700:#FF6347>⚔ Ruolo Elite ⚔</gradient>"
    lore:
      - ""
      - "<gradient:#FFFFFF:#E0E0E0>Ottieni il ruolo</gradient> &6Elite"
      - "<gradient:#87CEEB:#4682B4>nel server!</gradient>"
      - ""
      - "<gradient:#00FF00:#00CC00>▸ Vantaggi:</gradient>"
      - "<gradient:#FFD700:#FFA500>•</gradient> &e/fly <gradient:#808080:#606060>nel mondo principale</gradient>"
      - "<gradient:#FFD700:#FFA500>•</gradient> &eKit Elite <gradient:#808080:#606060>settimanale</gradient>"
      - "<gradient:#FFD700:#FFA500>•</gradient> &eTag speciale <gradient:#808080:#606060>in chat</gradient>"
      - ""
      - "<gradient:#00BFFF:#0080FF>► Prezzo:</gradient> &b{price} HiddenCoins"
      - ""
      - "<gradient:#00FF00:#00CC00>✦ Clicca per acquistare! ✦</gradient>"
    material: DIAMOND
    slot: 30
    coin-price: 500
    permission: group.elite
    command: "lp user {player} parent add elite"

  elite-plus:
    name: "<gradient:#FF1493:#4B0082>⚔ Ruolo Elite+ ⚔</gradient>"
    lore:
      - ""
      - "<gradient:#FFFFFF:#E0E0E0>Ottieni il ruolo</gradient> &dElite+"
      - "<gradient:#FF69B4:#FF1493>nel server!</gradient>"
      - ""
      - "<gradient:#00FF00:#00CC00>▸ Vantaggi:</gradient>"
      - "<gradient:#FF1493:#FF69B4>•</gradient> &eTutti i vantaggi Elite"
      - "<gradient:#FF1493:#FF69B4>•</gradient> &e/god <gradient:#808080:#606060>modalità dio</gradient>"
      - "<gradient:#FF1493:#FF69B4>•</gradient> &eKit Elite+ <gradient:#808080:#606060>giornaliero</gradient>"
      - "<gradient:#FF1493:#FF69B4>•</gradient> &eAccesso a &d/warp vip"
      - "<gradient:#FF1493:#FF69B4>•</gradient> &eTag animato <gradient:#808080:#606060>in chat</gradient>"
      - ""
      - "<gradient:#00BFFF:#0080FF>► Prezzo:</gradient> &b{price} HiddenCoins"
      - ""
      - "<gradient:#00FF00:#00CC00>✦ Clicca per acquistare! ✦</gradient>"
    material: NETHERITE_INGOT
    slot: 32
    coin-price: 1500
    permission: group.eliteplus
    command: "lp user {player} parent add eliteplus"

  fly-30days:
    name: "<gradient:#87CEEB:#00BFFF>☁ Fly 30 Giorni ☁</gradient>"
    lore:
      - ""
      - "<gradient:#FFFFFF:#E0E0E0>Ottieni il permesso di volo</gradient>"
      - "<gradient:#87CEEB:#00BFFF>per 30 giorni!</gradient>"
      - ""
      - "<gradient:#00BFFF:#0080FF>► Prezzo:</gradient> &b{price} HiddenCoins"
      - ""
      - "<gradient:#00FF00:#00CC00>✦ Clicca per acquistare! ✦</gradient>"
    material: FEATHER
    slot: 39
    coin-price: 300
    command: "lp user {player} permission settemp essentials.fly true 30d"

  special-key:
    name: "<gradient:#FF69B4:#FF1493>🔑 Chiave Speciale 🔑</gradient>"
    lore:
      - ""
      - "<gradient:#FFFFFF:#E0E0E0>Ottieni una</gradient> &dChiave Speciale"
      - "<gradient:#FF69B4:#FF1493>per aprire casse rare!</gradient>"
      - ""
      - "<gradient:#00BFFF:#0080FF>► Prezzo:</gradient> &b{price} HiddenCoins"
      - ""
      - "<gradient:#00FF00:#00CC00>✦ Clicca per acquistare! ✦</gradient>"
    material: TRIPWIRE_HOOK
    slot: 41
    coin-price: 200
    command: "crates give {player} special 1"

sounds:
  open:
    enabled: true
    sound: BLOCK_CHEST_OPEN
    volume: 0.5
    pitch: 1.2

  success:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP
    volume: 0.7
    pitch: 1.5

  error:
    enabled: true
    sound: ENTITY_VILLAGER_NO
    volume: 0.5
    pitch: 0.8

  click:
    enabled: true
    sound: UI_BUTTON_CLICK
    volume: 0.3
    pitch: 1.0